# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

plus_number <- function(number) {
    .Call(`_bioinfodb_plus_number`, number)
}

readGOFile <- function(filename) {
    .Call(`_bioinfodb_readGOFile`, filename)
}

rcpp_hello <- function() {
    .Call(`_bioinfodb_rcpp_hello`)
}

